accountIdentifier: <ACCOUNT_ID>
orgIdentifier: <ORG_ID>
projectIdentifier: <PROJECT_ID>
names: [<NAME>, <NAME2>, <NAME3>]
targetIdentifier: [<PIPELINE_ID>, <PIPELINE_ID2>, <PIPELINE_ID3>]
apiKey: <pat.XXXXX.YYYYY.ZZZZZ>